name: "MATLAB: test and coverage"

# Installs
# - MATLAB github action
# - MOXunit
# - MOcov
# Get test data
# cd into .github/workflows
# run .github/workflows/tests_matlab.m
# If tests pass, uploads coverage to codecov

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  matlab_tests:

    strategy:
      matrix:
        version: [R2021a, R2021b, R2022a, R2022b]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false  # Don't cancel all jobs if one fails

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install MAT
        uses: matlab-actions/setup-matlab@v1.2.4
        with:
          release: ${{ matrix.version }}

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Install Moxunit and MOcov
        run: |
          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
          git clone https://github.com/MOcov/MOcov.git --depth 1

      - name: Run tests
        uses: matlab-actions/run-command@v1.1.3
        with:
          command:
            cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows'));
            run run_tests_ci;

      - name: Check logs unix
        if: contains(fromJSON('["ubuntu", "macos"]'), matrix.os)
        run: cat test_report.log | grep 0

      - name: Check logs windows
        if: contains(fromJSON('["windows"]'), matrix.os)
        run: Get-Content test_report.log | Select-String -Pattern "0"

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          flags: ${{ matrix.os }} - matlab ${{ matrix.version }}
          name: codecov-umbrella
          fail_ci_if_error: true
