name: "Octave: test and coverage"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  octave_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y install octave liboctave-dev

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Compile JSONio
        run: |
          cd lib/JSONio
          mkoctfile --mex jsonread.c jsmn.c -DJSMN_PARENT_LINKS

      - name: MOxUnit Action
        uses: joergbrech/moxunit-action@v1.3.0
        with:
          tests: tests
          src: src
          ext: lib/JSONio tests/utils # External resources to add to the search put (excluded from coverage)
          with_coverage: true
          cover_xml_file: coverage.xml

      # - name: Code coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     file: coverage.xml # optional
      #     flags: unittests # optional
      #     name: codecov-umbrella # optional
      #     fail_ci_if_error: true # optional (default = false)
